t = int(input())
for i in range(0, t):
    s = input()
    ln = len(s)
    c = 0
    for j in range(0, ln):
        if(s[j] == 'a'):
            c += 1
        elif(s[j] == 'b'):
            c += 2
        elif(s[j] == 'c'):
            c += 3
        elif(s[j] == 'd'):
            c += 1
        elif(s[j] == 'e'):
            c += 2
        elif(s[j] == 'f'):
            c += 3
        elif(s[j] == 'g'):
            c += 1
        elif(s[j] == 'h'):
            c += 2
        elif(s[j] == 'i'):
            c += 3
        elif(s[j] == 'j'):
            c += 1
        elif(s[j] == 'k'):
            c += 2
        elif(s[j] == 'l'):
            c += 3
        elif(s[j] == 'm'):
            c += 1
        elif(s[j] == 'n'):
            c += 2
        elif(s[j] == 'o'):
            c += 3
        elif(s[j] == 'p'):
            c += 1
        elif(s[j] == 'q'):
            c += 2
        elif(s[j] == 'r'):
            c += 3
        elif(s[j] == 's'):
            c += 4
        elif(s[j] == 't'):
            c += 1
        elif(s[j] == 'u'):
            c += 2
        elif(s[j] == 'v'):
            c += 3
        elif(s[j] == 'w'):
            c += 1
        elif(s[j] == 'x'):
            c += 2
        elif(s[j] == 'y'):
            c += 3
        elif(s[j] == 'z'):
            c += 4
        elif(s[j] == ' '):
            c += 1
    print("Case #%d: %d" % (i+1, c))
